#define _XOPEN_SOURCE 700

#include <errno.h>
#include <libpq-fe.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include "auth.h"
#include "db.h"

#define MAX_PREPARED_STATEMENTS 128

static char prepared_statements[MAX_PREPARED_STATEMENTS][64];
static size_t prepared_statement_count = 0;
static char* global_connection_string = NULL;

static const char* SCHEMA_SQL =
    "SET statement_timeout = '15s';"
    "SET lock_timeout = '5s';"
    "SET idle_in_transaction_session_timeout = '30s';"
    "CREATE TABLE IF NOT EXISTS users ("
    "    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
    "    username       TEXT UNIQUE NOT NULL,"
    "    password_hash  TEXT NOT NULL,"
    "    role           TEXT NOT NULL DEFAULT 'viewer',"
    "    email          TEXT,"
    "    full_name      TEXT,"
    "    is_active      INTEGER NOT NULL DEFAULT 1,"
    "    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),"
    "    last_login     TIMESTAMP"
    ");"
    "CREATE TABLE IF NOT EXISTS categories ("
    "    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
    "    name           TEXT UNIQUE NOT NULL,"
    "    description    TEXT,"
    "    created_at     TIMESTAMP NOT NULL DEFAULT NOW()"
    ");"
    "CREATE TABLE IF NOT EXISTS items ("
    "    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
    "    sku            TEXT UNIQUE NOT NULL,"
    "    name           TEXT NOT NULL,"
    "    description    TEXT,"
    "    condition      TEXT NOT NULL DEFAULT 'Working',"
    "    category_id    INTEGER REFERENCES categories(id) ON DELETE SET NULL,"
    "    quantity       INTEGER NOT NULL DEFAULT 0,"
    "    min_quantity   INTEGER NOT NULL DEFAULT 0,"
    "    unit_price     DOUBLE PRECISION NOT NULL DEFAULT 0.0,"
    "    supplier       TEXT,"
    "    location       TEXT,"
    "    is_active      INTEGER NOT NULL DEFAULT 1,"
    "    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),"
    "    updated_at     TIMESTAMP NOT NULL DEFAULT NOW()"
    ");"
    "CREATE TABLE IF NOT EXISTS transactions ("
    "    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
    "    item_id        INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,"
    "    user_id        INTEGER REFERENCES users(id) ON DELETE SET NULL,"
    "    type           TEXT NOT NULL,"
    "    quantity       INTEGER NOT NULL,"
    "    unit_price     DOUBLE PRECISION,"
    "    notes          TEXT,"
    "    reference      TEXT,"
    "    created_at     TIMESTAMP NOT NULL DEFAULT NOW()"
    ");"
    "CREATE TABLE IF NOT EXISTS issue_records ("
    "    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
    "    item_id               INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,"
    "    issued_by             INTEGER REFERENCES users(id) ON DELETE SET NULL,"
    "    returned_by           INTEGER REFERENCES users(id) ON DELETE SET NULL,"
    "    quantity              INTEGER NOT NULL,"
    "    quantity_returned     INTEGER NOT NULL DEFAULT 0,"
    "    assignee              TEXT NOT NULL,"
    "    issued_to             TEXT,"
    "    purpose               TEXT,"
    "    reference             TEXT,"
    "    issue_date            TIMESTAMP NOT NULL DEFAULT NOW(),"
    "    return_date           TIMESTAMP,"
    "    expected_return_date  TIMESTAMP,"
    "    actual_return_date    TIMESTAMP,"
    "    unit_price            DOUBLE PRECISION NOT NULL DEFAULT 0.0,"
    "    status                TEXT NOT NULL DEFAULT 'ISSUED',"
    "    return_condition      TEXT,"
    "    return_notes          TEXT,"
    "    created_at            TIMESTAMP NOT NULL DEFAULT NOW()"
    ");"
    "CREATE TABLE IF NOT EXISTS audit_log ("
    "    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
    "    user_id        INTEGER REFERENCES users(id),"
    "    action         TEXT NOT NULL,"
    "    target         TEXT,"
    "    details        TEXT,"
    "    created_at     TIMESTAMP NOT NULL DEFAULT NOW()"
    ");"
    "CREATE TABLE IF NOT EXISTS backup_history ("
    "    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
    "    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),"
    "    size_kb        DOUBLE PRECISION NOT NULL DEFAULT 0,"
    "    provider       TEXT NOT NULL DEFAULT 'local',"
    "    url            TEXT,"
    "    status         TEXT NOT NULL DEFAULT 'OK',"
    "    notes          TEXT,"
    "    created_by     INTEGER REFERENCES users(id),"
    "    is_local       INTEGER NOT NULL DEFAULT 1,"
    "    local_path     TEXT"
    ");"
    "CREATE TABLE IF NOT EXISTS app_settings ("
    "    key            TEXT PRIMARY KEY,"
    "    value          TEXT NOT NULL,"
    "    updated_at     TIMESTAMP NOT NULL DEFAULT NOW()"
    ");"
    "CREATE INDEX IF NOT EXISTS idx_items_sku ON items(sku);"
    "CREATE INDEX IF NOT EXISTS idx_items_category ON items(category_id);"
    "CREATE INDEX IF NOT EXISTS idx_transactions_item ON transactions(item_id);"
    "CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(created_at);"
    "CREATE INDEX IF NOT EXISTS idx_audit_date ON audit_log(created_at);"
    "CREATE INDEX IF NOT EXISTS idx_issues_item ON issue_records(item_id);"
    "CREATE INDEX IF NOT EXISTS idx_issues_status ON issue_records(status);"
    "CREATE INDEX IF NOT EXISTS idx_issues_issue_date ON issue_records(issue_date);";

static const char* USER_SELECT_SQL =
    "SELECT id, username, password_hash, role, COALESCE(email, ''), "
    "COALESCE(full_name, ''), is_active, "
    "COALESCE(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS'), ''), "
    "COALESCE(TO_CHAR(last_login, 'YYYY-MM-DD HH24:MI:SS'), '') "
    "FROM users";

static const char* USER_SELECT_AUTH_SQL =
    "SELECT id, username, password_hash, role, COALESCE(email, ''), "
    "COALESCE(full_name, ''), is_active, "
    "COALESCE(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS'), ''), "
    "COALESCE(TO_CHAR(last_login, 'YYYY-MM-DD HH24:MI:SS'), '') "
    "FROM users WHERE username = $1 AND is_active = 1";

static const char* USER_SELECT_BY_ID_SQL =
    "SELECT id, username, password_hash, role, COALESCE(email, ''), "
    "COALESCE(full_name, ''), is_active, "
    "COALESCE(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS'), ''), "
    "COALESCE(TO_CHAR(last_login, 'YYYY-MM-DD HH24:MI:SS'), '') "
    "FROM users WHERE id = $1::int";

static const char* USER_SELECT_BY_USERNAME_SQL =
    "SELECT id, username, password_hash, role, COALESCE(email, ''), "
    "COALESCE(full_name, ''), is_active, "
    "COALESCE(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS'), ''), "
    "COALESCE(TO_CHAR(last_login, 'YYYY-MM-DD HH24:MI:SS'), '') "
    "FROM users WHERE username = $1";

static const char* USER_SELECT_ALL_ACTIVE_SQL =
    "SELECT id, username, password_hash, role, COALESCE(email, ''), "
    "COALESCE(full_name, ''), is_active, "
    "COALESCE(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS'), ''), "
    "COALESCE(TO_CHAR(last_login, 'YYYY-MM-DD HH24:MI:SS'), '') "
    "FROM users WHERE is_active = 1 ORDER BY id";

static void copy_text(char* dest, size_t dest_size, const char* src) {
    if (!dest || dest_size == 0) return;
    if (!src) src = "";
    snprintf(dest, dest_size, "%s", src);
}

static const char* normalize_item_condition(const char* condition) {
    if (!condition || condition[0] == '\0') return "Working";
    if (strcasecmp(condition, "Working") == 0) return "Working";
    if (strcasecmp(condition, "Damaged") == 0) return "Damaged";
    if (strcasecmp(condition, "Under Repair") == 0) return "Under Repair";
    return "Working";
}

static int exec_simple(PGconn* conn, const char* sql) {
    PGresult* result = PQexec(conn, sql);
    ExecStatusType status = PQresultStatus(result);
    if (status != PGRES_COMMAND_OK && status != PGRES_TUPLES_OK) {
        fprintf(stderr, "[db] SQL error: %s\n", PQerrorMessage(conn));
        PQclear(result);
        return 0;
    }
    PQclear(result);
    return 1;
}

static int is_prepared(const char* name) {
    size_t i;
    for (i = 0; i < prepared_statement_count; i++) {
        if (strcmp(prepared_statements[i], name) == 0) {
            return 1;
        }
    }
    return 0;
}

static int mark_prepared(const char* name) {
    if (prepared_statement_count >= MAX_PREPARED_STATEMENTS) {
        fprintf(stderr, "[db] Prepared statement registry exhausted\n");
        return 0;
    }
    snprintf(prepared_statements[prepared_statement_count],
             sizeof(prepared_statements[prepared_statement_count]), "%s", name);
    prepared_statement_count++;
    return 1;
}

static int ensure_prepared(PGconn* conn, const char* name, const char* sql, int n_params) {
    PGresult* result;

    if (is_prepared(name)) {
        return 1;
    }

    result = PQprepare(conn, name, sql, n_params, NULL);
    if (PQresultStatus(result) != PGRES_COMMAND_OK) {
        fprintf(stderr, "[db] Failed to prepare %s: %s\n", name, PQerrorMessage(conn));
        PQclear(result);
        return 0;
    }

    PQclear(result);
    return mark_prepared(name);
}

static PGresult* exec_prepared_stmt(PGconn* conn, const char* name, const char* sql,
                                    int n_params, const char* const* values) {
    if (!ensure_prepared(conn, name, sql, n_params)) {
        return NULL;
    }
    return PQexecPrepared(conn, name, n_params, values, NULL, NULL, 0);
}

static const char* result_value(PGresult* result, int row, int column) {
    if (!result || PQgetisnull(result, row, column)) {
        return "";
    }
    return PQgetvalue(result, row, column);
}

static int result_int(PGresult* result, int row, int column) {
    return atoi(result_value(result, row, column));
}

static double result_double(PGresult* result, int row, int column) {
    return atof(result_value(result, row, column));
}

static void rollback(PGconn* conn) {
    exec_simple(conn, "ROLLBACK");
}

static int begin_transaction(PGconn* conn) {
    return exec_simple(conn, "BEGIN");
}

static int commit_transaction(PGconn* conn) {
    return exec_simple(conn, "COMMIT");
}

static time_t parse_timestamp(const char* value) {
    struct tm tm_value;
    char* parsed = NULL;

    if (!value || value[0] == '\0') {
        return (time_t)-1;
    }

    memset(&tm_value, 0, sizeof(tm_value));
    parsed = strptime(value, "%Y-%m-%d %H:%M:%S", &tm_value);
    if (!parsed) {
        memset(&tm_value, 0, sizeof(tm_value));
        parsed = strptime(value, "%Y-%m-%d", &tm_value);
    }

    if (!parsed) {
        return (time_t)-1;
    }

    tm_value.tm_isdst = -1;
    return mktime(&tm_value);
}

static void compute_issue_status(IssueRecord* issue) {
    time_t now_value;
    time_t issue_time;

    if (!issue) return;
    if (strcmp(issue->status, "RETURNED") == 0 || issue->return_date[0] != '\0') return;

    issue_time = parse_timestamp(issue->issue_date);
    if (issue_time == (time_t)-1) return;

    now_value = time(NULL);
    if (difftime(now_value, issue_time) > (14 * 24 * 60 * 60)) {
        copy_text(issue->status, sizeof(issue->status), "OVERDUE");
    }
}

static void load_user_from_result(PGresult* result, int row, User* user) {
    memset(user, 0, sizeof(*user));
    user->id = result_int(result, row, 0);
    copy_text(user->username, sizeof(user->username), result_value(result, row, 1));
    copy_text(user->role, sizeof(user->role), result_value(result, row, 3));
    copy_text(user->email, sizeof(user->email), result_value(result, row, 4));
    copy_text(user->full_name, sizeof(user->full_name), result_value(result, row, 5));
    user->is_active = result_int(result, row, 6);
    copy_text(user->created_at, sizeof(user->created_at), result_value(result, row, 7));
    copy_text(user->last_login, sizeof(user->last_login), result_value(result, row, 8));
}

static void load_item_from_result(PGresult* result, int row, Item* item) {
    memset(item, 0, sizeof(*item));
    item->id = result_int(result, row, 0);
    copy_text(item->sku, sizeof(item->sku), result_value(result, row, 1));
    copy_text(item->name, sizeof(item->name), result_value(result, row, 2));
    copy_text(item->description, sizeof(item->description), result_value(result, row, 3));
    copy_text(item->condition, sizeof(item->condition), result_value(result, row, 4));
    item->category_id = result_int(result, row, 5);
    item->quantity = result_int(result, row, 6);
    item->min_quantity = result_int(result, row, 7);
    item->unit_price = result_double(result, row, 8);
    copy_text(item->supplier, sizeof(item->supplier), result_value(result, row, 9));
    copy_text(item->location, sizeof(item->location), result_value(result, row, 10));
    item->is_active = result_int(result, row, 11);
    copy_text(item->created_at, sizeof(item->created_at), result_value(result, row, 12));
    copy_text(item->updated_at, sizeof(item->updated_at), result_value(result, row, 13));
    copy_text(item->category_name, sizeof(item->category_name), result_value(result, row, 14));
}

static void load_transaction_from_result(PGresult* result, int row, Transaction* tx) {
    memset(tx, 0, sizeof(*tx));
    tx->id = result_int(result, row, 0);
    tx->item_id = result_int(result, row, 1);
    tx->user_id = result_int(result, row, 2);
    copy_text(tx->type, sizeof(tx->type), result_value(result, row, 3));
    tx->quantity = result_int(result, row, 4);
    tx->unit_price = result_double(result, row, 5);
    copy_text(tx->notes, sizeof(tx->notes), result_value(result, row, 6));
    copy_text(tx->reference, sizeof(tx->reference), result_value(result, row, 7));
    copy_text(tx->created_at, sizeof(tx->created_at), result_value(result, row, 8));
}

static void load_issue_from_result(PGresult* result, int row, IssueRecord* issue) {
    memset(issue, 0, sizeof(*issue));
    issue->id = result_int(result, row, 0);
    issue->item_id = result_int(result, row, 1);
    issue->issued_by = result_int(result, row, 2);
    issue->returned_by = result_int(result, row, 3);
    issue->quantity = result_int(result, row, 4);
    issue->quantity_returned = result_int(result, row, 5);
    copy_text(issue->assignee, sizeof(issue->assignee), result_value(result, row, 6));
    copy_text(issue->issued_to, sizeof(issue->issued_to), result_value(result, row, 7));
    if (issue->issued_to[0] == '\0') {
        copy_text(issue->issued_to, sizeof(issue->issued_to), issue->assignee);
    }
    copy_text(issue->purpose, sizeof(issue->purpose), result_value(result, row, 8));
    copy_text(issue->reference, sizeof(issue->reference), result_value(result, row, 9));
    copy_text(issue->issue_date, sizeof(issue->issue_date), result_value(result, row, 10));
    copy_text(issue->return_date, sizeof(issue->return_date), result_value(result, row, 11));
    copy_text(issue->expected_return_date, sizeof(issue->expected_return_date), result_value(result, row, 12));
    copy_text(issue->actual_return_date, sizeof(issue->actual_return_date), result_value(result, row, 13));
    issue->unit_price = result_double(result, row, 14);
    copy_text(issue->status, sizeof(issue->status), result_value(result, row, 15));
    copy_text(issue->return_condition, sizeof(issue->return_condition), result_value(result, row, 16));
    copy_text(issue->return_notes, sizeof(issue->return_notes), result_value(result, row, 17));
    copy_text(issue->created_at, sizeof(issue->created_at), result_value(result, row, 18));
    compute_issue_status(issue);
}

static int column_exists(PGconn* conn, const char* table, const char* column) {
    const char* sql =
        "SELECT 1 "
        "FROM information_schema.columns "
        "WHERE table_schema = 'public' AND table_name = $1 AND column_name = $2";
    const char* values[2] = {table, column};
    PGresult* result = exec_prepared_stmt(conn, "column_exists", sql, 2, values);
    int found = 0;

    if (!result) return 0;

    if (PQresultStatus(result) == PGRES_TUPLES_OK && PQntuples(result) > 0) {
        found = 1;
    }

    PQclear(result);
    return found;
}

static void ensure_column(PGconn* conn, const char* table, const char* column, const char* definition) {
    char sql[512];

    if (column_exists(conn, table, column)) {
        return;
    }

    snprintf(sql, sizeof(sql), "ALTER TABLE %s ADD COLUMN %s %s", table, column, definition);
    exec_simple(conn, sql);
}

static void apply_schema_migrations(PGconn* conn) {
    ensure_column(conn, "items", "condition", "TEXT NOT NULL DEFAULT 'Working'");
    ensure_column(conn, "issue_records", "issued_to", "TEXT");
    ensure_column(conn, "issue_records", "issue_date", "TIMESTAMP");
    ensure_column(conn, "issue_records", "return_date", "TIMESTAMP");

    exec_simple(conn,
        "UPDATE items SET condition='Working' WHERE condition IS NULL OR condition='';"
        "UPDATE issue_records SET issued_to=assignee WHERE issued_to IS NULL OR issued_to='';"
        "UPDATE issue_records SET issue_date=created_at WHERE issue_date IS NULL;"
        "UPDATE issue_records SET return_date=actual_return_date "
        "WHERE return_date IS NULL AND actual_return_date IS NOT NULL;");
}

static long query_count(PGconn* conn, const char* stmt_name, const char* sql) {
    PGresult* result = exec_prepared_stmt(conn, stmt_name, sql, 0, NULL);
    long count = 0;

    if (!result) return 0;
    if (PQresultStatus(result) == PGRES_TUPLES_OK && PQntuples(result) == 1) {
        count = atol(result_value(result, 0, 0));
    }
    PQclear(result);
    return count;
}

static int run_process(char* const argv[]) {
    pid_t pid = fork();
    int status = 0;

    if (pid < 0) {
        return 0;
    }

    if (pid == 0) {
        execvp(argv[0], argv);
        _exit(127);
    }

    if (waitpid(pid, &status, 0) < 0) {
        return 0;
    }

    return WIFEXITED(status) && WEXITSTATUS(status) == 0;
}

PGconn* db_init(const char* connection_string) {
    PGconn* conn;

    if (global_connection_string) {
        free(global_connection_string);
        global_connection_string = NULL;
    }

    conn = PQconnectdb(connection_string);
    if (PQstatus(conn) != CONNECTION_OK) {
        fprintf(stderr, "[db] Cannot connect to PostgreSQL: %s\n", PQerrorMessage(conn));
        PQfinish(conn);
        return NULL;
    }

    prepared_statement_count = 0;
    global_connection_string = strdup(connection_string);
    if (!global_connection_string) {
        fprintf(stderr, "[db] Failed to store connection string\n");
        PQfinish(conn);
        return NULL;
    }

    if (!exec_simple(conn,
            "SET statement_timeout = '15s';"
            "SET lock_timeout = '5s';"
            "SET idle_in_transaction_session_timeout = '30s';")) {
        db_close(conn);
        return NULL;
    }

    return conn;
}

void db_close(PGconn* conn) {
    if (conn) {
        PQfinish(conn);
    }
    if (global_connection_string) {
        free(global_connection_string);
        global_connection_string = NULL;
    }
    prepared_statement_count = 0;
}

void db_create_schema(PGconn* conn) {
    if (!exec_simple(conn, SCHEMA_SQL)) {
        return;
    }
    apply_schema_migrations(conn);
}

void db_seed_data(PGconn* conn) {
    const char* admin_username = getenv("NEXUS_INIT_USERNAME");
    const char* admin_password = getenv("NEXUS_INIT_PASSWORD");
    const char* admin_full_name = getenv("NEXUS_INIT_FULLNAME");
    const char* admin_email = getenv("NEXUS_INIT_EMAIL");
    long item_count;
    int i;

    static const struct {
        const char* sku;
        const char* name;
        const char* description;
        const char* condition;
        int quantity;
        int min_quantity;
        double unit_price;
        const char* supplier;
        const char* location;
    } seed_items[] = {
        {"NB-001", "Raspberry Pi 4", "Primary control board for edge deployments", "Working", 8, 3, 75.00, "PiShop", "Shelf A1"},
        {"NB-002", "USB Barcode Scanner", "Handheld scanner for stock intake", "Damaged", 4, 2, 28.50, "ScanTech", "Drawer B2"},
        {"NB-003", "Ethernet Cable 5m", "Cat6 cable for workstation and router links", "Working", 15, 5, 6.99, "CableHub", "Bin C3"},
        {"NB-004", "Thermal Label Roll", "Consumable labels for item tagging", "Under Repair", 12, 4, 9.25, "LabelWorks", "Shelf D1"},
        {"NB-005", "Power Adapter 12V", "Replacement adapter for field devices", "Working", 6, 2, 18.75, "VoltSupply", "Rack E4"}
    };

    if (!admin_username || admin_username[0] == '\0') admin_username = getenv("APP_USERNAME");
    if (!admin_password || admin_password[0] == '\0') admin_password = getenv("APP_PASSWORD");

    item_count = query_count(conn, "seed_item_count", "SELECT COUNT(*) FROM items");
    if (item_count == 0) {
        for (i = 0; i < (int)(sizeof(seed_items) / sizeof(seed_items[0])); i++) {
            char quantity_buf[16];
            char min_quantity_buf[16];
            char unit_price_buf[32];
            const char* values[10];
            PGresult* result;

            snprintf(quantity_buf, sizeof(quantity_buf), "%d", seed_items[i].quantity);
            snprintf(min_quantity_buf, sizeof(min_quantity_buf), "%d", seed_items[i].min_quantity);
            snprintf(unit_price_buf, sizeof(unit_price_buf), "%.2f", seed_items[i].unit_price);

            values[0] = seed_items[i].sku;
            values[1] = seed_items[i].name;
            values[2] = seed_items[i].description;
            values[3] = seed_items[i].condition;
            values[4] = NULL;
            values[5] = quantity_buf;
            values[6] = min_quantity_buf;
            values[7] = unit_price_buf;
            values[8] = seed_items[i].supplier;
            values[9] = seed_items[i].location;

            result = exec_prepared_stmt(
                conn,
                "seed_item_insert",
                "INSERT INTO items (sku, name, description, condition, category_id, quantity, "
                "min_quantity, unit_price, supplier, location) "
                "VALUES ($1, $2, $3, $4, $5::int, $6::int, $7::int, $8::double precision, $9, $10) "
                "ON CONFLICT (sku) DO NOTHING",
                10,
                values);
            if (result) {
                PQclear(result);
            }
        }
    }

    if (!admin_username || admin_username[0] == '\0' ||
        !admin_password || admin_password[0] == '\0') {
        fprintf(stderr,
            "[auth] No admin credentials set in environment.\n"
            "         Configure APP_USERNAME/APP_PASSWORD or NEXUS_INIT_USERNAME/NEXUS_INIT_PASSWORD.\n");
        return;
    }

    if (!admin_full_name || admin_full_name[0] == '\0') admin_full_name = admin_username;
    if (!admin_email || admin_email[0] == '\0') admin_email = "";

    {
        char* admin_hash = auth_hash_password(admin_password);
        const char* values[5];
        PGresult* result;

        values[0] = admin_username;
        values[1] = admin_hash;
        values[2] = "admin";
        values[3] = admin_full_name;
        values[4] = admin_email;

        result = exec_prepared_stmt(
            conn,
            "seed_admin_user",
            "INSERT INTO users (username, password_hash, role, full_name, email) "
            "VALUES ($1, $2, $3, $4, $5) "
            "ON CONFLICT (username) DO NOTHING",
            5,
            values);
        if (result) {
            PQclear(result);
        }
        free(admin_hash);
    }
}

User* db_authenticate(PGconn* conn, const char* username, const char* password) {
    const char* values[1] = {username};
    PGresult* result = exec_prepared_stmt(
        conn,
        "db_authenticate",
        USER_SELECT_AUTH_SQL,
        1,
        values);
    User* user = NULL;

    if (!result) return NULL;
    if (PQresultStatus(result) != PGRES_TUPLES_OK || PQntuples(result) == 0) {
        PQclear(result);
        return NULL;
    }

    if (!auth_verify_password(password, result_value(result, 0, 2))) {
        PQclear(result);
        return NULL;
    }

    user = malloc(sizeof(User));
    if (!user) {
        PQclear(result);
        return NULL;
    }
    load_user_from_result(result, 0, user);
    PQclear(result);

    {
        char id_buf[16];
        const char* update_values[1];
        PGresult* update_result;

        snprintf(id_buf, sizeof(id_buf), "%d", user->id);
        update_values[0] = id_buf;
        update_result = exec_prepared_stmt(
            conn,
            "db_authenticate_update_login",
            "UPDATE users SET last_login = NOW() WHERE id = $1::int",
            1,
            update_values);
        if (update_result) {
            PQclear(update_result);
        }
    }

    return user;
}

User* db_get_user(PGconn* conn, int user_id) {
    char id_buf[16];
    const char* values[1];
    PGresult* result;
    User* user;

    snprintf(id_buf, sizeof(id_buf), "%d", user_id);
    values[0] = id_buf;
    result = exec_prepared_stmt(
        conn,
        "db_get_user",
        USER_SELECT_BY_ID_SQL,
        1,
        values);
    if (!result) return NULL;
    if (PQresultStatus(result) != PGRES_TUPLES_OK || PQntuples(result) == 0) {
        PQclear(result);
        return NULL;
    }

    user = malloc(sizeof(User));
    if (!user) {
        PQclear(result);
        return NULL;
    }

    load_user_from_result(result, 0, user);
    PQclear(result);
    return user;
}

User* db_get_user_by_username(PGconn* conn, const char* username) {
    const char* values[1] = {username};
    PGresult* result = exec_prepared_stmt(
        conn,
        "db_get_user_by_username",
        USER_SELECT_BY_USERNAME_SQL,
        1,
        values);
    User* user;

    if (!result) return NULL;
    if (PQresultStatus(result) != PGRES_TUPLES_OK || PQntuples(result) == 0) {
        PQclear(result);
        return NULL;
    }

    user = malloc(sizeof(User));
    if (!user) {
        PQclear(result);
        return NULL;
    }

    load_user_from_result(result, 0, user);
    PQclear(result);
    return user;
}

User** db_get_all_users(PGconn* conn, int* count) {
    PGresult* result = exec_prepared_stmt(
        conn,
        "db_get_all_users",
        USER_SELECT_ALL_ACTIVE_SQL,
        0,
        NULL);
    User** users;
    int rows;
    int i;

    *count = 0;
    if (!result) return NULL;
    if (PQresultStatus(result) != PGRES_TUPLES_OK) {
        PQclear(result);
        return NULL;
    }

    rows = PQntuples(result);
    users = rows > 0 ? malloc((size_t)rows * sizeof(User*)) : NULL;
    if (rows > 0 && !users) {
        PQclear(result);
        return NULL;
    }

    for (i = 0; i < rows; i++) {
        users[i] = malloc(sizeof(User));
        if (!users[i]) {
            *count = i;
            PQclear(result);
            return users;
        }
        load_user_from_result(result, i, users[i]);
    }

    *count = rows;
    PQclear(result);
    return users;
}

int db_create_user(PGconn* conn, const char* username, const char* password,
                   const char* role, const char* full_name, const char* email) {
    char* hash = auth_hash_password(password);
    const char* values[5];
    PGresult* result;
    int ok = 0;

    values[0] = username;
    values[1] = hash;
    values[2] = role;
    values[3] = full_name;
    values[4] = email;

    result = exec_prepared_stmt(
        conn,
        "db_create_user",
        "INSERT INTO users (username, password_hash, role, full_name, email) "
        "VALUES ($1, $2, $3, $4, $5)",
        5,
        values);
    if (result && PQresultStatus(result) == PGRES_COMMAND_OK) {
        ok = 1;
    }
    if (result) PQclear(result);
    free(hash);
    return ok;
}

int db_update_user(PGconn* conn, int user_id, const char* role,
                   const char* full_name, const char* email, int is_active) {
    char id_buf[16];
    char active_buf[8];
    const char* values[5];
    PGresult* result;
    int ok = 0;

    snprintf(id_buf, sizeof(id_buf), "%d", user_id);
    snprintf(active_buf, sizeof(active_buf), "%d", is_active);

    values[0] = role;
    values[1] = full_name;
    values[2] = email;
    values[3] = active_buf;
    values[4] = id_buf;

    result = exec_prepared_stmt(
        conn,
        "db_update_user",
        "UPDATE users SET role = $1, full_name = $2, email = $3, is_active = $4::int WHERE id = $5::int",
        5,
        values);
    if (result && PQresultStatus(result) == PGRES_COMMAND_OK) ok = 1;
    if (result) PQclear(result);
    return ok;
}

int db_change_password(PGconn* conn, int user_id, const char* new_password) {
    char* hash = auth_hash_password(new_password);
    char id_buf[16];
    const char* values[2];
    PGresult* result;
    int ok = 0;

    snprintf(id_buf, sizeof(id_buf), "%d", user_id);
    values[0] = hash;
    values[1] = id_buf;

    result = exec_prepared_stmt(
        conn,
        "db_change_password",
        "UPDATE users SET password_hash = $1 WHERE id = $2::int",
        2,
        values);
    if (result && PQresultStatus(result) == PGRES_COMMAND_OK) ok = 1;
    if (result) PQclear(result);
    free(hash);
    return ok;
}

int db_delete_user(PGconn* conn, int user_id) {
    char id_buf[16];
    const char* values[1];
    PGresult* result;
    int ok = 0;

    snprintf(id_buf, sizeof(id_buf), "%d", user_id);
    values[0] = id_buf;

    result = exec_prepared_stmt(
        conn,
        "db_delete_user",
        "UPDATE users SET is_active = 0 WHERE id = $1::int",
        1,
        values);
    if (result && PQresultStatus(result) == PGRES_COMMAND_OK) ok = 1;
    if (result) PQclear(result);
    return ok;
}

Category** db_get_categories(PGconn* conn, int* count) {
    PGresult* result = exec_prepared_stmt(
        conn,
        "db_get_categories",
        "SELECT id, name, COALESCE(description, ''), "
        "COALESCE(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS'), '') "
        "FROM categories ORDER BY name",
        0,
        NULL);
    Category** categories;
    int rows;
    int i;

    *count = 0;
    if (!result) return NULL;
    if (PQresultStatus(result) != PGRES_TUPLES_OK) {
        PQclear(result);
        return NULL;
    }

    rows = PQntuples(result);
    categories = rows > 0 ? malloc((size_t)rows * sizeof(Category*)) : NULL;
    if (rows > 0 && !categories) {
        PQclear(result);
        return NULL;
    }

    for (i = 0; i < rows; i++) {
        categories[i] = malloc(sizeof(Category));
        if (!categories[i]) {
            *count = i;
            PQclear(result);
            return categories;
        }
        memset(categories[i], 0, sizeof(Category));
        categories[i]->id = result_int(result, i, 0);
        copy_text(categories[i]->name, sizeof(categories[i]->name), result_value(result, i, 1));
        copy_text(categories[i]->description, sizeof(categories[i]->description), result_value(result, i, 2));
        copy_text(categories[i]->created_at, sizeof(categories[i]->created_at), result_value(result, i, 3));
    }

    *count = rows;
    PQclear(result);
    return categories;
}

int db_create_category(PGconn* conn, const char* name, const char* description) {
    const char* values[2] = {name, description};
    PGresult* result = exec_prepared_stmt(
        conn,
        "db_create_category",
        "INSERT INTO categories (name, description) VALUES ($1, $2)",
        2,
        values);
    int ok = (result && PQresultStatus(result) == PGRES_COMMAND_OK);
    if (result) PQclear(result);
    return ok;
}

Item** db_get_items(PGconn* conn, const char* search, int category_id, int low_stock, int* count) {
    const char* sql =
        "SELECT i.id, i.sku, i.name, COALESCE(i.description, ''), COALESCE(i.condition, 'Working'), "
        "COALESCE(i.category_id, 0), i.quantity, i.min_quantity, i.unit_price, "
        "COALESCE(i.supplier, ''), COALESCE(i.location, ''), i.is_active, "
        "COALESCE(TO_CHAR(i.created_at, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(TO_CHAR(i.updated_at, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(c.name, '') "
        "FROM items i "
        "LEFT JOIN categories c ON i.category_id = c.id "
        "WHERE i.is_active = 1 "
        "AND ($1 = '' OR i.name ILIKE $2 OR i.sku ILIKE $2) "
        "AND ($3::int = 0 OR i.category_id = $3::int) "
        "AND ($4::int = 0 OR i.quantity <= i.min_quantity) "
        "ORDER BY i.name";
    char category_buf[16];
    char low_stock_buf[8];
    char pattern[320];
    const char* values[4];
    PGresult* result;
    Item** items;
    int rows;
    int i;

    *count = 0;
    snprintf(category_buf, sizeof(category_buf), "%d", category_id);
    snprintf(low_stock_buf, sizeof(low_stock_buf), "%d", low_stock ? 1 : 0);
    snprintf(pattern, sizeof(pattern), "%%%s%%", search ? search : "");
    values[0] = search ? search : "";
    values[1] = pattern;
    values[2] = category_buf;
    values[3] = low_stock_buf;

    result = exec_prepared_stmt(conn, "db_get_items", sql, 4, values);
    if (!result) return NULL;
    if (PQresultStatus(result) != PGRES_TUPLES_OK) {
        PQclear(result);
        return NULL;
    }

    rows = PQntuples(result);
    items = rows > 0 ? malloc((size_t)rows * sizeof(Item*)) : NULL;
    if (rows > 0 && !items) {
        PQclear(result);
        return NULL;
    }

    for (i = 0; i < rows; i++) {
        items[i] = malloc(sizeof(Item));
        if (!items[i]) {
            *count = i;
            PQclear(result);
            return items;
        }
        load_item_from_result(result, i, items[i]);
    }

    *count = rows;
    PQclear(result);
    return items;
}

Item* db_get_item(PGconn* conn, int item_id) {
    const char* sql =
        "SELECT i.id, i.sku, i.name, COALESCE(i.description, ''), COALESCE(i.condition, 'Working'), "
        "COALESCE(i.category_id, 0), i.quantity, i.min_quantity, i.unit_price, "
        "COALESCE(i.supplier, ''), COALESCE(i.location, ''), i.is_active, "
        "COALESCE(TO_CHAR(i.created_at, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(TO_CHAR(i.updated_at, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(c.name, '') "
        "FROM items i "
        "LEFT JOIN categories c ON i.category_id = c.id "
        "WHERE i.id = $1::int";
    char id_buf[16];
    const char* values[1];
    PGresult* result;
    Item* item;

    snprintf(id_buf, sizeof(id_buf), "%d", item_id);
    values[0] = id_buf;
    result = exec_prepared_stmt(conn, "db_get_item", sql, 1, values);
    if (!result) return NULL;
    if (PQresultStatus(result) != PGRES_TUPLES_OK || PQntuples(result) == 0) {
        PQclear(result);
        return NULL;
    }

    item = malloc(sizeof(Item));
    if (!item) {
        PQclear(result);
        return NULL;
    }
    load_item_from_result(result, 0, item);
    PQclear(result);
    return item;
}

int db_create_item(PGconn* conn, const char* sku, const char* name, const char* description,
                   int category_id, int quantity, int min_quantity, double unit_price,
                   const char* supplier, const char* location, const char* condition) {
    char category_buf[16];
    char quantity_buf[16];
    char min_quantity_buf[16];
    char unit_price_buf[32];
    const char* values[10];
    PGresult* result;
    int ok = 0;

    snprintf(category_buf, sizeof(category_buf), "%d", category_id);
    snprintf(quantity_buf, sizeof(quantity_buf), "%d", quantity);
    snprintf(min_quantity_buf, sizeof(min_quantity_buf), "%d", min_quantity);
    snprintf(unit_price_buf, sizeof(unit_price_buf), "%.2f", unit_price);

    values[0] = sku;
    values[1] = name;
    values[2] = description;
    values[3] = normalize_item_condition(condition);
    values[4] = category_id > 0 ? category_buf : NULL;
    values[5] = quantity_buf;
    values[6] = min_quantity_buf;
    values[7] = unit_price_buf;
    values[8] = supplier;
    values[9] = location;

    result = exec_prepared_stmt(
        conn,
        "db_create_item",
        "INSERT INTO items (sku, name, description, condition, category_id, quantity, "
        "min_quantity, unit_price, supplier, location) "
        "VALUES ($1, $2, $3, $4, $5::int, $6::int, $7::int, $8::double precision, $9, $10)",
        10,
        values);
    if (result && PQresultStatus(result) == PGRES_COMMAND_OK) ok = 1;
    if (result) PQclear(result);
    return ok;
}

int db_update_item(PGconn* conn, int item_id, const char* name, const char* description,
                   int category_id, int quantity, int min_quantity, double unit_price,
                   const char* supplier, const char* location, const char* condition) {
    char item_id_buf[16];
    char category_buf[16];
    char quantity_buf[16];
    char min_quantity_buf[16];
    char unit_price_buf[32];
    const char* values[10];
    PGresult* result;
    int ok = 0;

    snprintf(item_id_buf, sizeof(item_id_buf), "%d", item_id);
    snprintf(category_buf, sizeof(category_buf), "%d", category_id);
    snprintf(quantity_buf, sizeof(quantity_buf), "%d", quantity);
    snprintf(min_quantity_buf, sizeof(min_quantity_buf), "%d", min_quantity);
    snprintf(unit_price_buf, sizeof(unit_price_buf), "%.2f", unit_price);

    values[0] = name;
    values[1] = description;
    values[2] = normalize_item_condition(condition);
    values[3] = category_id > 0 ? category_buf : NULL;
    values[4] = quantity_buf;
    values[5] = min_quantity_buf;
    values[6] = unit_price_buf;
    values[7] = supplier;
    values[8] = location;
    values[9] = item_id_buf;

    result = exec_prepared_stmt(
        conn,
        "db_update_item",
        "UPDATE items SET name = $1, description = $2, condition = $3, category_id = $4::int, "
        "quantity = $5::int, min_quantity = $6::int, unit_price = $7::double precision, "
        "supplier = $8, location = $9, updated_at = NOW() WHERE id = $10::int",
        10,
        values);
    if (result && PQresultStatus(result) == PGRES_COMMAND_OK) ok = 1;
    if (result) PQclear(result);
    return ok;
}

int db_delete_item(PGconn* conn, int item_id) {
    char id_buf[16];
    const char* values[1];
    PGresult* result;
    int ok = 0;

    snprintf(id_buf, sizeof(id_buf), "%d", item_id);
    values[0] = id_buf;

    result = exec_prepared_stmt(
        conn,
        "db_delete_item",
        "UPDATE items SET is_active = 0 WHERE id = $1::int",
        1,
        values);
    if (result && PQresultStatus(result) == PGRES_COMMAND_OK) ok = 1;
    if (result) PQclear(result);
    return ok;
}

int db_adjust_stock(PGconn* conn, int item_id, int delta, int user_id,
                    const char* tx_type, double price, const char* notes, const char* ref) {
    char item_id_buf[16];
    char user_id_buf[16];
    char delta_buf[16];
    char new_qty_buf[16];
    char price_buf[32];
    const char* values[2];
    PGresult* result;
    int current_qty;
    int new_qty;
    int ok = 0;

    snprintf(item_id_buf, sizeof(item_id_buf), "%d", item_id);
    snprintf(user_id_buf, sizeof(user_id_buf), "%d", user_id);
    snprintf(delta_buf, sizeof(delta_buf), "%d", delta);
    snprintf(price_buf, sizeof(price_buf), "%.2f", price);

    if (!begin_transaction(conn)) return 0;

    values[0] = item_id_buf;
    result = exec_prepared_stmt(
        conn,
        "db_adjust_stock_lock_item",
        "SELECT quantity FROM items WHERE id = $1::int FOR UPDATE",
        1,
        values);
    if (!result || PQresultStatus(result) != PGRES_TUPLES_OK || PQntuples(result) == 0) {
        if (result) PQclear(result);
        rollback(conn);
        return 0;
    }

    current_qty = result_int(result, 0, 0);
    PQclear(result);
    new_qty = current_qty + delta;
    if (new_qty < 0) {
        rollback(conn);
        return 0;
    }

    snprintf(new_qty_buf, sizeof(new_qty_buf), "%d", new_qty);
    {
        const char* update_values[2] = {new_qty_buf, item_id_buf};
        result = exec_prepared_stmt(
            conn,
            "db_adjust_stock_update_item",
            "UPDATE items SET quantity = $1::int, updated_at = NOW() WHERE id = $2::int",
            2,
            update_values);
        if (!result || PQresultStatus(result) != PGRES_COMMAND_OK) {
            if (result) PQclear(result);
            rollback(conn);
            return 0;
        }
        PQclear(result);
    }

    {
        const char* tx_values[7] = {
            item_id_buf, user_id_buf, tx_type, delta_buf, price_buf,
            notes ? notes : "", ref ? ref : ""
        };
        result = exec_prepared_stmt(
            conn,
            "db_adjust_stock_insert_tx",
            "INSERT INTO transactions (item_id, user_id, type, quantity, unit_price, notes, reference) "
            "VALUES ($1::int, $2::int, $3, $4::int, $5::double precision, $6, $7)",
            7,
            tx_values);
        if (!result || PQresultStatus(result) != PGRES_COMMAND_OK) {
            if (result) PQclear(result);
            rollback(conn);
            return 0;
        }
        PQclear(result);
    }

    ok = commit_transaction(conn);
    if (!ok) rollback(conn);
    return ok;
}

Transaction** db_get_transactions(PGconn* conn, const char* search, int* count) {
    const char* sql =
        "SELECT id, item_id, COALESCE(user_id, 0), type, quantity, COALESCE(unit_price, 0), "
        "COALESCE(notes, ''), COALESCE(reference, ''), "
        "COALESCE(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS'), '') "
        "FROM transactions "
        "WHERE ($1 = '' OR type ILIKE $2 OR notes ILIKE $2 OR reference ILIKE $2) "
        "ORDER BY created_at DESC";
    char pattern[320];
    const char* values[2];
    PGresult* result;
    Transaction** txs;
    int rows;
    int i;

    *count = 0;
    snprintf(pattern, sizeof(pattern), "%%%s%%", search ? search : "");
    values[0] = search ? search : "";
    values[1] = pattern;

    result = exec_prepared_stmt(conn, "db_get_transactions", sql, 2, values);
    if (!result) return NULL;
    if (PQresultStatus(result) != PGRES_TUPLES_OK) {
        PQclear(result);
        return NULL;
    }

    rows = PQntuples(result);
    txs = rows > 0 ? malloc((size_t)rows * sizeof(Transaction*)) : NULL;
    if (rows > 0 && !txs) {
        PQclear(result);
        return NULL;
    }

    for (i = 0; i < rows; i++) {
        txs[i] = malloc(sizeof(Transaction));
        if (!txs[i]) {
            *count = i;
            PQclear(result);
            return txs;
        }
        load_transaction_from_result(result, i, txs[i]);
    }

    *count = rows;
    PQclear(result);
    return txs;
}

IssueRecord** db_get_issues(PGconn* conn, const char* search, const char* status, int* count) {
    const char* sql =
        "SELECT id, item_id, COALESCE(issued_by, 0), COALESCE(returned_by, 0), quantity, quantity_returned, "
        "COALESCE(assignee, ''), COALESCE(issued_to, ''), COALESCE(purpose, ''), COALESCE(reference, ''), "
        "COALESCE(TO_CHAR(issue_date, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(TO_CHAR(return_date, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(TO_CHAR(expected_return_date, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(TO_CHAR(actual_return_date, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(unit_price, 0), "
        "CASE "
        "    WHEN return_date IS NULL AND status <> 'RETURNED' AND issue_date < NOW() - INTERVAL '14 days' THEN 'OVERDUE' "
        "    ELSE status "
        "END, "
        "COALESCE(return_condition, ''), COALESCE(return_notes, ''), "
        "COALESCE(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS'), '') "
        "FROM issue_records "
        "WHERE ($1 = '' OR assignee ILIKE $2 OR COALESCE(issued_to, '') ILIKE $2 OR "
        "       COALESCE(purpose, '') ILIKE $2 OR COALESCE(reference, '') ILIKE $2) "
        "AND ($3 = '' OR "
        "     CASE WHEN return_date IS NULL AND status <> 'RETURNED' AND issue_date < NOW() - INTERVAL '14 days' "
        "          THEN 'OVERDUE' ELSE status END = $3) "
        "ORDER BY issue_date DESC";
    char pattern[320];
    const char* values[3];
    PGresult* result;
    IssueRecord** issues;
    int rows;
    int i;

    *count = 0;
    snprintf(pattern, sizeof(pattern), "%%%s%%", search ? search : "");
    values[0] = search ? search : "";
    values[1] = pattern;
    values[2] = status ? status : "";

    result = exec_prepared_stmt(conn, "db_get_issues", sql, 3, values);
    if (!result) return NULL;
    if (PQresultStatus(result) != PGRES_TUPLES_OK) {
        PQclear(result);
        return NULL;
    }

    rows = PQntuples(result);
    issues = rows > 0 ? malloc((size_t)rows * sizeof(IssueRecord*)) : NULL;
    if (rows > 0 && !issues) {
        PQclear(result);
        return NULL;
    }

    for (i = 0; i < rows; i++) {
        issues[i] = malloc(sizeof(IssueRecord));
        if (!issues[i]) {
            *count = i;
            PQclear(result);
            return issues;
        }
        load_issue_from_result(result, i, issues[i]);
    }

    *count = rows;
    PQclear(result);
    return issues;
}

IssueRecord** db_get_overdue_issues(PGconn* conn, int* count) {
    const char* sql =
        "SELECT id, item_id, COALESCE(issued_by, 0), COALESCE(returned_by, 0), quantity, quantity_returned, "
        "COALESCE(assignee, ''), COALESCE(issued_to, ''), COALESCE(purpose, ''), COALESCE(reference, ''), "
        "COALESCE(TO_CHAR(issue_date, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(TO_CHAR(return_date, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(TO_CHAR(expected_return_date, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(TO_CHAR(actual_return_date, 'YYYY-MM-DD HH24:MI:SS'), ''), "
        "COALESCE(unit_price, 0), 'OVERDUE', COALESCE(return_condition, ''), "
        "COALESCE(return_notes, ''), COALESCE(TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS'), '') "
        "FROM issue_records "
        "WHERE return_date IS NULL AND status <> 'RETURNED' AND issue_date < NOW() - INTERVAL '14 days' "
        "ORDER BY issue_date DESC";
    PGresult* result = exec_prepared_stmt(conn, "db_get_overdue_issues", sql, 0, NULL);
    IssueRecord** issues;
    int rows;
    int i;

    *count = 0;
    if (!result) return NULL;
    if (PQresultStatus(result) != PGRES_TUPLES_OK) {
        PQclear(result);
        return NULL;
    }

    rows = PQntuples(result);
    issues = rows > 0 ? malloc((size_t)rows * sizeof(IssueRecord*)) : NULL;
    if (rows > 0 && !issues) {
        PQclear(result);
        return NULL;
    }

    for (i = 0; i < rows; i++) {
        issues[i] = malloc(sizeof(IssueRecord));
        if (!issues[i]) {
            *count = i;
            PQclear(result);
            return issues;
        }
        load_issue_from_result(result, i, issues[i]);
        copy_text(issues[i]->status, sizeof(issues[i]->status), "OVERDUE");
    }

    *count = rows;
    PQclear(result);
    return issues;
}

int db_create_issue(PGconn* conn, int item_id, int user_id, int quantity,
                    const char* assignee, const char* purpose, const char* reference,
                    const char* expected_return, double unit_price, const char* issue_date) {
    char item_id_buf[16];
    char user_id_buf[16];
    char quantity_buf[16];
    char negative_qty_buf[16];
    char price_buf[32];
    char notes_buf[512];
    char issue_timestamp[32];
    int has_issue_date = issue_date && issue_date[0] != '\0';
    const char* values[1];
    PGresult* result;
    int available;
    int ok = 0;

    snprintf(item_id_buf, sizeof(item_id_buf), "%d", item_id);
    snprintf(user_id_buf, sizeof(user_id_buf), "%d", user_id);
    snprintf(quantity_buf, sizeof(quantity_buf), "%d", quantity);
    snprintf(negative_qty_buf, sizeof(negative_qty_buf), "%d", -quantity);
    snprintf(price_buf, sizeof(price_buf), "%.2f", unit_price);
    snprintf(notes_buf, sizeof(notes_buf), "Issued to: %s | %s", assignee ? assignee : "", purpose ? purpose : "");
    if (has_issue_date) {
        snprintf(issue_timestamp, sizeof(issue_timestamp), "%s 00:00:00", issue_date);
    } else {
        issue_timestamp[0] = '\0';
    }

    if (!begin_transaction(conn)) return 0;

    values[0] = item_id_buf;
    result = exec_prepared_stmt(
        conn,
        "db_create_issue_lock_item",
        "SELECT quantity FROM items WHERE id = $1::int AND is_active = 1 FOR UPDATE",
        1,
        values);
    if (!result || PQresultStatus(result) != PGRES_TUPLES_OK || PQntuples(result) == 0) {
        if (result) PQclear(result);
        rollback(conn);
        return 0;
    }

    available = result_int(result, 0, 0);
    PQclear(result);
    if (available < quantity) {
        rollback(conn);
        return 0;
    }

    {
        const char* update_values[2] = {quantity_buf, item_id_buf};
        result = exec_prepared_stmt(
            conn,
            "db_create_issue_reduce_stock",
            "UPDATE items SET quantity = quantity - $1::int, updated_at = NOW() WHERE id = $2::int",
            2,
            update_values);
        if (!result || PQresultStatus(result) != PGRES_COMMAND_OK) {
            if (result) PQclear(result);
            rollback(conn);
            return 0;
        }
        PQclear(result);
    }

    {
        const char* tx_values[7] = {
            item_id_buf,
            user_id_buf,
            "ISSUE",
            negative_qty_buf,
            price_buf,
            notes_buf,
            has_issue_date ? issue_timestamp : NULL
        };
        result = exec_prepared_stmt(
            conn,
            "db_create_issue_insert_tx",
            "INSERT INTO transactions (item_id, user_id, type, quantity, unit_price, notes, created_at) "
            "VALUES ($1::int, $2::int, $3, $4::int, $5::double precision, $6, COALESCE($7::timestamp, NOW()))",
            7,
            tx_values);
        if (!result || PQresultStatus(result) != PGRES_COMMAND_OK) {
            if (result) PQclear(result);
            rollback(conn);
            return 0;
        }
        PQclear(result);
    }

    {
        const char* issue_values[11] = {
            item_id_buf,
            user_id_buf,
            quantity_buf,
            assignee ? assignee : "",
            assignee ? assignee : "",
            purpose ? purpose : "",
            reference ? reference : "",
            has_issue_date ? issue_timestamp : NULL,
            expected_return && expected_return[0] != '\0' ? expected_return : NULL,
            price_buf,
            has_issue_date ? issue_timestamp : NULL
        };
        result = exec_prepared_stmt(
            conn,
            "db_create_issue_insert_issue",
            "INSERT INTO issue_records (item_id, issued_by, quantity, assignee, issued_to, purpose, "
            "reference, issue_date, expected_return_date, unit_price, status, created_at) "
            "VALUES ($1::int, $2::int, $3::int, $4, $5, $6, $7, COALESCE($8::timestamp, NOW()), "
            "$9::timestamp, $10::double precision, 'ISSUED', COALESCE($11::timestamp, NOW()))",
            11,
            issue_values);
        if (!result || PQresultStatus(result) != PGRES_COMMAND_OK) {
            if (result) PQclear(result);
            rollback(conn);
            return 0;
        }
        PQclear(result);
    }

    ok = commit_transaction(conn);
    if (!ok) rollback(conn);
    return ok;
}

int db_return_issue(PGconn* conn, int issue_id, int user_id, int quantity_returned,
                    const char* condition, const char* notes) {
    char issue_id_buf[16];
    char user_id_buf[16];
    char returned_buf[16];
    const char* values[1];
    PGresult* result;
    int original_qty;
    int returned_qty;
    int item_id;
    int outstanding;
    int new_returned;
    int ok = 0;

    snprintf(issue_id_buf, sizeof(issue_id_buf), "%d", issue_id);
    snprintf(user_id_buf, sizeof(user_id_buf), "%d", user_id);
    snprintf(returned_buf, sizeof(returned_buf), "%d", quantity_returned);

    if (!begin_transaction(conn)) return 0;

    values[0] = issue_id_buf;
    result = exec_prepared_stmt(
        conn,
        "db_return_issue_lock_issue",
        "SELECT quantity, quantity_returned, item_id FROM issue_records WHERE id = $1::int FOR UPDATE",
        1,
        values);
    if (!result || PQresultStatus(result) != PGRES_TUPLES_OK || PQntuples(result) == 0) {
        if (result) PQclear(result);
        rollback(conn);
        return 0;
    }

    original_qty = result_int(result, 0, 0);
    returned_qty = result_int(result, 0, 1);
    item_id = result_int(result, 0, 2);
    PQclear(result);

    outstanding = original_qty - returned_qty;
    if (quantity_returned > outstanding) {
        rollback(conn);
        return 0;
    }

    new_returned = returned_qty + quantity_returned;
    {
        char new_returned_buf[16];
        char item_id_buf[16];
        const char* update_values[6];

        snprintf(new_returned_buf, sizeof(new_returned_buf), "%d", new_returned);
        snprintf(item_id_buf, sizeof(item_id_buf), "%d", item_id);

        update_values[0] = new_returned_buf;
        update_values[1] = (new_returned >= original_qty) ? "RETURNED" : "PARTIAL";
        update_values[2] = user_id_buf;
        update_values[3] = condition ? condition : "";
        update_values[4] = notes ? notes : "";
        update_values[5] = issue_id_buf;

        result = exec_prepared_stmt(
            conn,
            "db_return_issue_update_issue",
            "UPDATE issue_records SET quantity_returned = $1::int, status = $2, returned_by = $3::int, "
            "actual_return_date = CASE WHEN $2 = 'RETURNED' THEN NOW() ELSE NULL END, "
            "return_date = CASE WHEN $2 = 'RETURNED' THEN NOW() ELSE NULL END, "
            "return_condition = $4, return_notes = $5 WHERE id = $6::int",
            6,
            update_values);
        if (!result || PQresultStatus(result) != PGRES_COMMAND_OK) {
            if (result) PQclear(result);
            rollback(conn);
            return 0;
        }
        PQclear(result);

        {
            const char* restore_values[2] = {returned_buf, item_id_buf};
            result = exec_prepared_stmt(
                conn,
                "db_return_issue_restore_stock",
                "UPDATE items SET quantity = quantity + $1::int, updated_at = NOW() WHERE id = $2::int",
                2,
                restore_values);
            if (!result || PQresultStatus(result) != PGRES_COMMAND_OK) {
                if (result) PQclear(result);
                rollback(conn);
                return 0;
            }
            PQclear(result);
        }
    }

    ok = commit_transaction(conn);
    if (!ok) rollback(conn);
    return ok;
}

char* db_backup_to_file(PGconn* conn, const char* backup_path) {
    char* message;
    char* argv[8];
    (void)conn;

    if (!global_connection_string || !backup_path) {
        message = malloc(128);
        if (message) copy_text(message, 128, "Invalid PostgreSQL backup parameters");
        return message;
    }

    argv[0] = "pg_dump";
    argv[1] = "--clean";
    argv[2] = "--if-exists";
    argv[3] = "--no-owner";
    argv[4] = "--file";
    argv[5] = (char*)backup_path;
    argv[6] = global_connection_string;
    argv[7] = NULL;

    message = malloc(512);
    if (!message) return NULL;

    if (run_process(argv)) {
        snprintf(message, 512, "Backup created successfully at %s", backup_path);
    } else {
        snprintf(message, 512, "Backup failed. Ensure pg_dump is installed and the connection string is valid.");
    }
    return message;
}

int db_restore_from_file(PGconn* conn, const char* backup_path) {
    char* argv[7];
    (void)conn;

    if (!global_connection_string || !backup_path) {
        return 0;
    }

    argv[0] = "psql";
    argv[1] = "--set";
    argv[2] = "ON_ERROR_STOP=1";
    argv[3] = "--file";
    argv[4] = (char*)backup_path;
    argv[5] = global_connection_string;
    argv[6] = NULL;

    return run_process(argv);
}

void free_users(User** users, int count) {
    int i;
    if (!users) return;
    for (i = 0; i < count; i++) free(users[i]);
    free(users);
}

void free_items(Item** items, int count) {
    int i;
    if (!items) return;
    for (i = 0; i < count; i++) free(items[i]);
    free(items);
}

void free_categories(Category** categories, int count) {
    int i;
    if (!categories) return;
    for (i = 0; i < count; i++) free(categories[i]);
    free(categories);
}

void free_transactions(Transaction** txs, int count) {
    int i;
    if (!txs) return;
    for (i = 0; i < count; i++) free(txs[i]);
    free(txs);
}

void free_issues(IssueRecord** issues, int count) {
    int i;
    if (!issues) return;
    for (i = 0; i < count; i++) free(issues[i]);
    free(issues);
}

void db_save_setting(PGconn* conn, const char* key, const char* value) {
    const char* values[2];
    PGresult* result;

    if (!conn || !key || !value) return;

    values[0] = key;
    values[1] = value;
    result = exec_prepared_stmt(
        conn,
        "db_save_setting",
        "INSERT INTO app_settings (key, value, updated_at) "
        "VALUES ($1, $2, NOW()) "
        "ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at",
        2,
        values);
    if (result) PQclear(result);
}

char* db_get_setting(PGconn* conn, const char* key) {
    const char* values[1];
    PGresult* result;
    char* output;

    if (!conn || !key) {
        output = malloc(1);
        if (output) output[0] = '\0';
        return output;
    }

    values[0] = key;
    result = exec_prepared_stmt(
        conn,
        "db_get_setting",
        "SELECT COALESCE(value, '') FROM app_settings WHERE key = $1",
        1,
        values);
    if (!result || PQresultStatus(result) != PGRES_TUPLES_OK || PQntuples(result) == 0) {
        if (result) PQclear(result);
        output = malloc(1);
        if (output) output[0] = '\0';
        return output;
    }

    output = malloc(256);
    if (output) {
        copy_text(output, 256, result_value(result, 0, 0));
    }
    PQclear(result);
    return output;
}

int db_save_backup_record(PGconn* conn, double size_kb, const char* provider,
                         const char* url, const char* status, const char* notes,
                         int created_by, int is_local, const char* local_path) {
    char size_buf[32];
    char created_by_buf[16];
    char is_local_buf[8];
    const char* values[8];
    PGresult* result;
    int last_id = -1;

    if (!conn) return -1;

    snprintf(size_buf, sizeof(size_buf), "%.2f", size_kb);
    snprintf(created_by_buf, sizeof(created_by_buf), "%d", created_by);
    snprintf(is_local_buf, sizeof(is_local_buf), "%d", is_local);

    values[0] = size_buf;
    values[1] = provider ? provider : "local";
    values[2] = url ? url : "";
    values[3] = status ? status : "OK";
    values[4] = notes ? notes : "";
    values[5] = created_by > 0 ? created_by_buf : NULL;
    values[6] = is_local_buf;
    values[7] = local_path ? local_path : "";

    result = exec_prepared_stmt(
        conn,
        "db_save_backup_record",
        "INSERT INTO backup_history (size_kb, provider, url, status, notes, created_by, is_local, local_path) "
        "VALUES ($1::double precision, $2, $3, $4, $5, $6::int, $7::int, $8) RETURNING id",
        8,
        values);
    if (result && PQresultStatus(result) == PGRES_TUPLES_OK && PQntuples(result) == 1) {
        last_id = result_int(result, 0, 0);
    }
    if (result) PQclear(result);
    return last_id;
}
